<?php
define('ABSPATH', dirname(__FILE__) . '/../../../');
require_once ABSPATH . 'wp-load.php';
header('Content-Type: text/plain; charset=utf-8');

$translations = [
39 => [
'short' => 'Epithalón es un tetrapéptido sintético de investigación con la secuencia de aminoácidos Ala-Glu-Asp-Gly. Se estudia por sus efectos potenciales sobre la actividad de la telomerasa y su papel en el envejecimiento celular y la longevidad.',
'desc' => '<h3>Descripción General</h3><p>Epithalón es un tetrapéptido sintético de investigación con la secuencia Ala-Glu-Asp-Gly. Es estudiado por sus efectos sobre la actividad de la telomerasa, la enzima responsable de mantener la longitud de los telómeros, estructuras protectoras en los extremos de los cromosomas.</p><h3>Mecanismo de Acción</h3><p>Epithalón estimula la producción de telomerasa, lo que puede contribuir a la elongación y mantenimiento de los telómeros, retrasando el acortamiento asociado al envejecimiento celular.</p><h3>Áreas de Investigación</h3><ul><li>Actividad de la telomerasa y longitud telomérica</li><li>Envejecimiento celular y longevidad</li><li>Regulación del ritmo circadiano</li><li>Función neuroendocrina y pineal</li><li>Propiedades antioxidantes celulares</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
41 => [
'short' => 'PT-141, también conocido como Bremelanotida, es un péptido sintético derivado del sistema de melanocortina reconocido por su papel en la señalización del sistema nervioso central relacionada con la motivación y la función sexual.',
'desc' => '<h3>Descripción General</h3><p>Erosense™ (PT-141 / Bremelanotida) es un péptido sintético derivado del sistema de melanocortina. Se investiga por su papel en la señalización del sistema nervioso central relacionada con la motivación y la función sexual.</p><h3>Mecanismo de Acción</h3><p>PT-141 actúa como agonista de los receptores de melanocortina MC3R y MC4R en el sistema nervioso central, activando vías de señalización dopaminérgicas implicadas en la excitación y la respuesta sexual.</p><h3>Áreas de Investigación</h3><ul><li>Disfunción sexual masculina y femenina</li><li>Señalización de melanocortina central</li><li>Vías dopaminérgicas y motivación</li><li>Deseo sexual hipoactivo</li><li>Neurociencia de la función sexual</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
43 => [
'short' => 'Kisspeptina es un neuropéptido de origen natural que desempeña un papel central en la regulación del eje hipotalámico-hipofisario-gonadal (HPG). Se reconoce como un activador clave de la liberación de hormona liberadora de gonadotropinas (GnRH).',
'desc' => '<h3>Descripción General</h3><p>FertiNova™ (Kisspeptina) es un neuropéptido que desempeña un papel central en la regulación del eje hipotalámico-hipofisario-gonadal (HPG). Es reconocido como un activador clave de la liberación de GnRH, la hormona que inicia la cascada reproductiva.</p><h3>Mecanismo de Acción</h3><p>Kisspeptina se une al receptor GPR54 (KISS1R) en las neuronas GnRH del hipotálamo, estimulando la liberación pulsátil de GnRH y, consecuentemente, de LH y FSH desde la hipófisis.</p><h3>Áreas de Investigación</h3><ul><li>Regulación de la fertilidad y la reproducción</li><li>Eje hipotalámico-hipofisario-gonadal</li><li>Pubertad y desarrollo sexual</li><li>Fecundación in vitro (FIV)</li><li>Hipogonadismo y amenorrea</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
45 => [
'short' => 'GHRP-2 (Péptido Liberador de Hormona de Crecimiento-2) es un hexapéptido sintético reconocido por su capacidad para estimular la liberación de hormona de crecimiento (GH) mediante la activación del receptor de grelina (GHS-R1a).',
'desc' => '<h3>Descripción General</h3><p>GHR-Prime™ (GHRP-2) es un hexapéptido sintético reconocido por su capacidad para estimular la liberación de hormona de crecimiento (GH) a través de la activación del receptor de grelina (GHS-R1a) en la hipófisis anterior.</p><h3>Mecanismo de Acción</h3><p>GHRP-2 se une al receptor de secretagogos de GH (GHS-R1a), activando la liberación pulsátil de GH desde la hipófisis. También suprime la somatostatina, el inhibidor natural de la GH.</p><h3>Áreas de Investigación</h3><ul><li>Estimulación de la hormona de crecimiento</li><li>Composición corporal y masa muscular</li><li>Metabolismo de grasas y lipólisis</li><li>Regeneración tisular y recuperación</li><li>Calidad del sueño y ritmo circadiano</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
47 => [
'short' => 'El Glutatión es un tripéptido de origen natural compuesto por ácido glutámico, cisteína y glicina. Es reconocido como uno de los antioxidantes intracelulares más importantes, desempeñando un papel central en la defensa contra el estrés oxidativo.',
'desc' => '<h3>Descripción General</h3><p>GlutaPureX™ (Glutatión) es un tripéptido compuesto por ácido glutámico, cisteína y glicina. Es reconocido como el antioxidante intracelular más importante del organismo, fundamental en la defensa contra el estrés oxidativo y la desintoxicación celular.</p><h3>Mecanismo de Acción</h3><p>El glutatión neutraliza directamente los radicales libres, regenera otros antioxidantes (vitaminas C y E), y participa en la conjugación y eliminación de toxinas a través del sistema enzimático glutatión S-transferasa.</p><h3>Áreas de Investigación</h3><ul><li>Defensa antioxidante y estrés oxidativo</li><li>Desintoxicación hepática</li><li>Función inmunológica</li><li>Protección celular y mitocondrial</li><li>Envejecimiento y longevidad celular</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
49 => [
'short' => 'La Gonadotropina Menopáusica Humana (HMG) es un complejo de gonadotropinas purificadas compuesto principalmente por hormona foliculoestimulante (FSH) y hormona luteinizante (LH). Se investiga en estudios de fertilidad y función reproductiva.',
'desc' => '<h3>Descripción General</h3><p>GonodoMax™ (HMG) es un complejo de gonadotropinas purificadas compuesto por FSH y LH. Es investigado extensamente en el contexto de la fertilidad, la estimulación ovárica y la espermatogénesis.</p><h3>Mecanismo de Acción</h3><p>La FSH estimula el desarrollo folicular en los ovarios y la espermatogénesis en los testículos, mientras que la LH promueve la ovulación y la producción de testosterona en las células de Leydig.</p><h3>Áreas de Investigación</h3><ul><li>Estimulación de la fertilidad</li><li>Protocolos de fecundación in vitro</li><li>Espermatogénesis y función testicular</li><li>Hipogonadismo hipogonadotrópico</li><li>Regulación del eje reproductivo</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
51 => [
'short' => 'Sermorelina es un análogo peptídico sintético de la hormona liberadora de hormona de crecimiento (GHRH) que estimula la liberación natural de GH desde la hipófisis anterior de manera pulsátil y fisiológica.',
'desc' => '<h3>Descripción General</h3><p>GrowthPrime™ (Sermorelina) es un análogo sintético de la GHRH que estimula la liberación natural y pulsátil de hormona de crecimiento desde la hipófisis anterior, respetando los mecanismos de retroalimentación fisiológica del organismo.</p><h3>Mecanismo de Acción</h3><p>Se une al receptor de GHRH en las células somatotropas de la hipófisis anterior, estimulando la síntesis y liberación de GH de forma dosis-dependiente, manteniendo los ritmos circadianos naturales.</p><h3>Áreas de Investigación</h3><ul><li>Estimulación fisiológica de la hormona de crecimiento</li><li>Envejecimiento y deficiencia de GH</li><li>Composición corporal y masa magra</li><li>Calidad del sueño y recuperación</li><li>Densidad ósea y metabolismo</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
53 => [
'short' => 'El Factor de Crecimiento Similar a la Insulina 1 Long Arg3 (IGF-1 LR3) es un análogo modificado del IGF-1 nativo con una vida media extendida y mayor potencia biológica. Se investiga por su papel en el crecimiento celular y la hipertrofia muscular.',
'desc' => '<h3>Descripción General</h3><p>IGF-Novax™ (IGF-1 LR3) es un análogo modificado del IGF-1 nativo, diseñado con mayor vida media y potencia biológica. Se investiga por su papel en la proliferación celular, el crecimiento muscular y la regeneración tisular.</p><h3>Mecanismo de Acción</h3><p>IGF-1 LR3 se une al receptor de IGF-1 con menor afinidad por las proteínas de unión a IGF (IGFBPs), lo que resulta en una mayor biodisponibilidad y actividad biológica prolongada en los tejidos diana.</p><h3>Áreas de Investigación</h3><ul><li>Hipertrofia muscular y crecimiento celular</li><li>Regeneración y reparación tisular</li><li>Metabolismo de la glucosa</li><li>Supervivencia celular y anti-apoptosis</li><li>Rendimiento deportivo y recuperación</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
55 => [
'short' => 'Timosina Alfa-1 (Tα1) es un péptido inmunomodulador de origen natural derivado de la proteína tímica protimosin alfa. Se investiga por su capacidad para modular y fortalecer la respuesta inmune adaptativa e innata.',
'desc' => '<h3>Descripción General</h3><p>ImmunoThyx™ (Timosina Alfa-1) es un péptido inmunomodulador de origen natural derivado del timo. Es investigado por su capacidad para fortalecer tanto la inmunidad innata como la adaptativa.</p><h3>Mecanismo de Acción</h3><p>Tα1 activa las células dendríticas, potencia la maduración de linfocitos T, aumenta la producción de citocinas Th1 y mejora la capacidad de presentación antigénica del sistema inmune.</p><h3>Áreas de Investigación</h3><ul><li>Inmunomodulación y fortalecimiento inmune</li><li>Inmunodeficiencias y terapias adyuvantes</li><li>Infecciones virales crónicas (hepatitis B/C)</li><li>Oncología e inmunoterapia</li><li>Vacunación y respuesta inmune</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
57 => [
'short' => 'Ipamoreina es un péptido liberador de hormona de crecimiento (GHRP) sintético que estimula selectivamente la secreción de GH con mínimos efectos secundarios sobre el cortisol, la prolactina y el apetito.',
'desc' => '<h3>Descripción General</h3><p>IpaGrow™ (Ipamoreina) es un GHRP sintético que estimula selectivamente la secreción de GH con alta especificidad, minimizando los efectos secundarios sobre cortisol, prolactina y apetito que presentan otros secretagogos.</p><h3>Mecanismo de Acción</h3><p>Se une selectivamente al receptor GHS-R1a en la hipófisis, estimulando la liberación pulsátil de GH sin afectar significativamente otros ejes hormonales, lo que le confiere un perfil de seguridad superior.</p><h3>Áreas de Investigación</h3><ul><li>Estimulación selectiva de hormona de crecimiento</li><li>Composición corporal y reducción de grasa</li><li>Recuperación muscular y regeneración</li><li>Calidad del sueño profundo</li><li>Densidad ósea y salud articular</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
];

$updated = 0;
foreach ($translations as $id => $data) {
    $r = wp_update_post(['ID'=>$id,'post_content'=>$data['desc'],'post_excerpt'=>$data['short']], true);
    if (!is_wp_error($r)) { $updated++; echo "OK: ID $id\n"; } else { echo "ERR: ID $id\n"; }
}
echo "\nBatch 2: $updated / " . count($translations) . "\n";
