<?php
define('ABSPATH', dirname(__FILE__) . '/../../../');
require_once ABSPATH . 'wp-load.php';
header('Content-Type: text/plain; charset=utf-8');

$translations = [
59 => [
'short' => 'KLOW es un péptido sintético de investigación formulado para el estudio de la hidratación celular, la regulación metabólica y la optimización de los procesos de recuperación a nivel tisular.',
'desc' => '<h3>Descripción General</h3><p>KlowXtreme™ es un péptido sintético formulado para estudios avanzados en hidratación celular, regulación metabólica y optimización de la recuperación tisular.</p><h3>Áreas de Investigación</h3><ul><li>Hidratación y equilibrio celular</li><li>Regulación metabólica avanzada</li><li>Recuperación y reparación tisular</li><li>Rendimiento y resistencia</li><li>Homeostasis electrolítica</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
61 => [
'short' => 'LL-37 es un péptido sintético de investigación derivado de la catelicidina antimicrobiana humana. Se investiga por sus potentes propiedades antimicrobianas, inmunomoduladoras y de curación de heridas.',
'desc' => '<h3>Descripción General</h3><p>LL-Guard™ (LL-37) es un péptido antimicrobiano derivado de la catelicidina humana hCAP-18. Es investigado por sus potentes propiedades antimicrobianas de amplio espectro y su capacidad inmunomoduladora.</p><h3>Mecanismo de Acción</h3><p>LL-37 desestabiliza las membranas bacterianas, modula la respuesta inmune innata, promueve la quimiotaxis de células inmunes y estimula la angiogénesis en el proceso de curación de heridas.</p><h3>Áreas de Investigación</h3><ul><li>Actividad antimicrobiana de amplio espectro</li><li>Modulación de la inmunidad innata</li><li>Curación de heridas y regeneración</li><li>Biofilms y resistencia bacteriana</li><li>Enfermedades inflamatorias de la piel</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
63 => [
'short' => 'GLOW es una formulación peptídica sintética de investigación desarrollada para estudios avanzados en regeneración celular cutánea, luminosidad y protección contra el envejecimiento prematuro de la piel.',
'desc' => '<h3>Descripción General</h3><p>Luminax™ (GLOW) es una formulación peptídica desarrollada para investigación avanzada en regeneración celular cutánea, protección contra el fotoenvejecimiento y optimización de la función de barrera de la piel.</p><h3>Áreas de Investigación</h3><ul><li>Regeneración celular cutánea</li><li>Protección contra el fotoenvejecimiento</li><li>Luminosidad y tono uniforme de la piel</li><li>Síntesis de colágeno dérmico</li><li>Función de barrera epidérmica</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
65 => [
'short' => 'MOTS-C es un péptido derivado de la mitocondria codificado por el ADN mitocondrial, reconocido por su papel en la regulación del metabolismo energético, la sensibilidad a la insulina y la homeostasis celular.',
'desc' => '<h3>Descripción General</h3><p>MitoCoreX™ (MOTS-C) es un péptido derivado del ADN mitocondrial, investigado por su papel fundamental en la regulación del metabolismo energético, la sensibilidad a la insulina y la homeostasis metabólica celular.</p><h3>Mecanismo de Acción</h3><p>MOTS-C activa la vía AMPK, regula el metabolismo de la glucosa y los ácidos grasos, y modula la función mitocondrial. También influye en la expresión génica nuclear a través de la señalización retrógrada mitocondria-núcleo.</p><h3>Áreas de Investigación</h3><ul><li>Metabolismo energético mitocondrial</li><li>Sensibilidad a la insulina y metabolismo de glucosa</li><li>Envejecimiento metabólico y longevidad</li><li>Rendimiento físico y ejercicio</li><li>Homeostasis celular y estrés metabólico</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
67 => [
'short' => 'SS-31, también conocido como Elamipretida, es un péptido sintético dirigido a las mitocondrias, diseñado para proteger y restaurar la función mitocondrial al estabilizar la cardiolipina en la membrana mitocondrial interna.',
'desc' => '<h3>Descripción General</h3><p>MitoShield™ (SS-31 / Elamipretida) es un péptido sintético dirigido a las mitocondrias. Es investigado por su capacidad para proteger y restaurar la función mitocondrial mediante la estabilización de la cardiolipina.</p><h3>Mecanismo de Acción</h3><p>SS-31 penetra selectivamente en la membrana mitocondrial interna y se une a la cardiolipina, estabilizando la cadena de transporte de electrones, reduciendo la producción de especies reactivas de oxígeno (ROS) y optimizando la producción de ATP.</p><h3>Áreas de Investigación</h3><ul><li>Disfunción mitocondrial y enfermedades mitocondriales</li><li>Protección cardíaca y cardiomiopatía</li><li>Envejecimiento y sarcopenia</li><li>Enfermedades neurodegenerativas</li><li>Lesión por isquemia-reperfusión</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
69 => [
'short' => 'La Nicotinamida Adenina Dinucleótido (NAD+) es una coenzima crítica presente en cada célula del organismo. Es esencial para el metabolismo energético, la reparación del ADN y la regulación del envejecimiento celular.',
'desc' => '<h3>Descripción General</h3><p>NAD+ (Nicotinamida Adenina Dinucleótido) es una coenzima esencial para el metabolismo energético celular, la reparación del ADN, la señalización celular y la regulación de los procesos de envejecimiento.</p><h3>Mecanismo de Acción</h3><p>NAD+ funciona como cofactor en las reacciones redox de la cadena respiratoria mitocondrial, activa las sirtuinas (SIRT1-7) implicadas en la longevidad, y es sustrato de las enzimas PARP de reparación del ADN.</p><h3>Áreas de Investigación</h3><ul><li>Metabolismo energético y función mitocondrial</li><li>Envejecimiento y longevidad celular</li><li>Reparación del ADN y estabilidad genómica</li><li>Neuroprotección y función cognitiva</li><li>Activación de sirtuinas y autofagia</li></ul><h3>Especificaciones</h3><p>Liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
70 => [
'short' => 'SEMAX es un neuropéptido sintético derivado del fragmento de la hormona adrenocorticotrópica (ACTH). Se investiga por sus efectos neuroprotectores, neurotróficos y potenciadores de la función cognitiva.',
'desc' => '<h3>Descripción General</h3><p>NeuroMaxide™ (SEMAX) es un neuropéptido sintético derivado del fragmento ACTH(4-10). Es investigado por sus efectos neuroprotectores, neurotróficos y su capacidad para potenciar la función cognitiva y la memoria.</p><h3>Mecanismo de Acción</h3><p>SEMAX aumenta la expresión de BDNF (factor neurotrófico derivado del cerebro) y otros factores neurotróficos, modula los sistemas de neurotransmisores dopaminérgicos y serotoninérgicos, y reduce el estrés oxidativo cerebral.</p><h3>Áreas de Investigación</h3><ul><li>Neuroprotección y enfermedades neurodegenerativas</li><li>Función cognitiva, memoria y aprendizaje</li><li>Recuperación de accidentes cerebrovasculares</li><li>Expresión de factores neurotróficos (BDNF)</li><li>Trastornos de ansiedad y estrés</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
72 => [
'short' => 'ARA-290, también conocido como Cibinetida, es un péptido sintético derivado de la región protectora de la eritropoyetina (EPO). Se investiga por sus propiedades neuroprotectoras, antiinflamatorias y de reparación tisular.',
'desc' => '<h3>Descripción General</h3><p>NeuroVascX™ (ARA-290 / Cibinetida) es un péptido derivado de la región tisular protectora de la EPO. Se investiga por sus propiedades neuroprotectoras, antiinflamatorias y reparadoras sin los efectos eritropoyéticos de la EPO completa.</p><h3>Mecanismo de Acción</h3><p>ARA-290 se une selectivamente al receptor heterodimérico de EPO/CD131, activando vías de señalización citoprotectoras y antiinflamatorias sin estimular la producción de glóbulos rojos.</p><h3>Áreas de Investigación</h3><ul><li>Neuropatía diabética y dolor neuropático</li><li>Neuroprotección y reparación nerviosa</li><li>Inflamación crónica y autoinmunidad</li><li>Protección tisular en isquemia</li><li>Curación de heridas crónicas</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
74 => [
'short' => 'La melatonina es una hormona indolamina endógena sintetizada principalmente en la glándula pineal. Regula el ritmo circadiano sueño-vigilia y posee propiedades antioxidantes y neuroprotectoras.',
'desc' => '<h3>Descripción General</h3><p>Nocturnax™ (Melatonina) es una hormona endógena sintetizada en la glándula pineal. Regula el ritmo circadiano y posee propiedades antioxidantes, inmunomoduladoras y neuroprotectoras.</p><h3>Mecanismo de Acción</h3><p>La melatonina se une a los receptores MT1 y MT2 en el núcleo supraquiasmático del hipotálamo, sincronizando los ritmos biológicos. También actúa como potente antioxidante directo neutralizando radicales libres.</p><h3>Áreas de Investigación</h3><ul><li>Regulación del ciclo sueño-vigilia</li><li>Propiedades antioxidantes y neuroprotectoras</li><li>Modulación del sistema inmune</li><li>Jet lag y trastornos del ritmo circadiano</li><li>Envejecimiento y función mitocondrial</li></ul><h3>Especificaciones</h3><p>Liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
76 => [
'short' => 'El Péptido Inductor del Sueño Delta (DSIP) es un neuropéptido de origen natural asociado con la regulación del sueño, la respuesta al estrés y la modulación neuroendocrina.',
'desc' => '<h3>Descripción General</h3><p>Noctyline™ (DSIP) es un neuropéptido de origen natural investigado por su papel en la inducción del sueño delta (ondas lentas), la modulación del estrés y la regulación neuroendocrina.</p><h3>Mecanismo de Acción</h3><p>DSIP modula las oscilaciones de ondas lentas durante el sueño NREM, influye en la liberación de cortisol y ACTH, y regula los patrones de liberación de hormona de crecimiento durante el sueño profundo.</p><h3>Áreas de Investigación</h3><ul><li>Inducción del sueño profundo (delta)</li><li>Regulación del estrés y cortisol</li><li>Modulación neuroendocrina</li><li>Insomnio y trastornos del sueño</li><li>Neuroprotección y recuperación</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
78 => [
'short' => 'La oxitocina es un neuropéptido y hormona de origen natural ampliamente estudiada por su papel en la vinculación social, el comportamiento maternal, la confianza interpersonal y la regulación del estrés.',
'desc' => '<h3>Descripción General</h3><p>Oxyluxe™ (Oxitocina) es un neuropéptido de origen natural investigado por su papel en la vinculación social, el comportamiento prosocial, la regulación emocional y la función reproductiva.</p><h3>Mecanismo de Acción</h3><p>La oxitocina se une a los receptores OTR en el sistema nervioso central y periférico, modulando la señalización GABAérgica, reduciendo la actividad de la amígdala y promoviendo comportamientos de vínculo y confianza.</p><h3>Áreas de Investigación</h3><ul><li>Vinculación social y comportamiento prosocial</li><li>Regulación del estrés y ansiedad</li><li>Trastornos del espectro autista</li><li>Función reproductiva y lactancia</li><li>Psicoterapia y salud mental</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
];

$updated = 0;
foreach ($translations as $id => $data) {
    $r = wp_update_post(['ID'=>$id,'post_content'=>$data['desc'],'post_excerpt'=>$data['short']], true);
    if (!is_wp_error($r)) { $updated++; echo "OK: ID $id\n"; } else { echo "ERR: ID $id\n"; }
}
echo "\nBatch 3: $updated / " . count($translations) . "\n";
