<?php
define('ABSPATH', dirname(__FILE__) . '/../../../');
require_once ABSPATH . 'wp-load.php';
header('Content-Type: text/plain; charset=utf-8');

// Full Spanish benefits for every product
$all_benefits = [
19 => "Activa la vía AMPK a nivel celular\nPromueve la captación de glucosa y la sensibilidad a la insulina\nEstimula la oxidación de ácidos grasos\nMejora la biogénesis mitocondrial\nModula el metabolismo energético celular\nEstudiado en modelos de resistencia metabólica\nApoya la investigación en rendimiento y ejercicio",
21 => "Estimula la lipólisis (descomposición de grasas)\nInhibe la lipogénesis (formación de grasas)\nSin impacto en los niveles de glucosa\nApoya la reparación del cartílago\nPromueve la regeneración ósea\nNo afecta la proliferación celular\nEstudiado para reducción de grasa corporal",
23 => "Regula la señalización central del apetito y la saciedad\nRalentiza el vaciamiento gástrico\nInfluye en las vías de ingesta energética\nActiva mecanismos mediados por receptores de amilina\nApoya la investigación en regulación del peso corporal\nMejora la comunicación cerebro-intestino\nEstudiado para modulación sinérgica metabólica",
25 => "Diluyente estéril para reconstitución de péptidos\nConservante bacteriostático (alcohol bencílico 0.9%)\nCompatible con la mayoría de péptidos liofilizados\nPermite múltiples extracciones del mismo vial\npH neutro y osmolaridad controlada\nGrado farmacéutico certificado\nAlmacenamiento seguro entre 2-8°C",
27 => "Modula la liberación de neurotransmisores\nInhibe la formación del complejo SNARE\nReduce la contracción muscular facial\nEstudiado para reducción de líneas de expresión\nAlternativa no invasiva a neurotoxinas\nApoya la investigación en dermatología\nFormulación de alta estabilidad",
29 => "Sinergia regenerativa BPC-157 + TB-500\nPromueve la reparación de tendones y ligamentos\nEstimula la angiogénesis y formación de vasos\nReduce la inflamación sistémica\nApoya la protección gastrointestinal\nMejora la migración y diferenciación celular\nEstudiado para recuperación de lesiones",
31 => "Promueve la reparación de tendones y músculos\nProtección y curación gastrointestinal\nReduce la inflamación tisular\nEstimula la angiogénesis (formación de vasos)\nApoya la regeneración nerviosa\nModula las vías del óxido nítrico\nEstudiado para curación acelerada de heridas",
33 => "Estimula la melanogénesis natural\nPromueve la producción de eumelanina\nActiva los receptores de melanocortina MC1R-MC5R\nEstudiado para fotoprotección UV\nApoya la investigación en pigmentación cutánea\nModula el apetito a nivel central\nInvestigado para función sexual",
35 => "Estimula la síntesis de colágeno y elastina\nPromueve la regeneración cutánea\nAcelera la curación de heridas\nActividad antioxidante celular\nApoya el crecimiento capilar\nModula la expresión génica de reparación\nEstudiado para antienvejecimiento dérmico",
37 => "Inhibe las vías inflamatorias NF-κB\nReduce la producción de citocinas proinflamatorias\nModula la respuesta inmune innata\nEstudiado para inflamación gastrointestinal\nPropiedades antimicrobianas\nApoya la curación de heridas\nInvestigado para condiciones inflamatorias cutáneas",
39 => "Estimula la actividad de la telomerasa\nApoya el mantenimiento de los telómeros\nModula el ritmo circadiano\nEstudiado para longevidad celular\nFunción neuroendocrina y pineal\nPropiedades antioxidantes celulares\nInvestigado para envejecimiento y senescencia",
41 => "Activa receptores de melanocortina MC3R y MC4R\nModula vías dopaminérgicas centrales\nEstudiado para disfunción sexual\nApoya la investigación en motivación sexual\nMecanismo de acción central (no periférico)\nInvestigado en ambos géneros\nPerfil de seguridad bien documentado",
43 => "Estimula la liberación pulsátil de GnRH\nRegula el eje hipotalámico-hipofisario-gonadal\nApoya la investigación en fertilidad\nEstudiado para protocolos de FIV\nModula la secreción de LH y FSH\nInvestigado para hipogonadismo\nMecanismo fisiológico de activación",
45 => "Estimula la liberación de hormona de crecimiento\nActiva el receptor de grelina GHS-R1a\nSuprime la somatostatina\nApoya la composición corporal y masa muscular\nPromueve la lipólisis y metabolismo de grasas\nMejora la calidad del sueño profundo\nEstudiado para regeneración tisular",
47 => "Potente antioxidante intracelular\nNeutraliza radicales libres directamente\nRegenera vitaminas C y E\nApoya la desintoxicación hepática\nFortalece la función inmunológica\nProtección celular y mitocondrial\nEstudiado para envejecimiento y longevidad",
49 => "Estimula el desarrollo folicular (FSH)\nPromueve la espermatogénesis\nApoya protocolos de fertilidad\nRegula la producción de testosterona\nEstudiado para fecundación in vitro\nModula el eje reproductivo\nInvestigado para hipogonadismo",
51 => "Estimula la liberación fisiológica de GH\nRespeta los ritmos circadianos naturales\nMejora la composición corporal\nApoya la calidad del sueño y recuperación\nPromueve la densidad ósea\nEstudiado para deficiencia de GH\nPerfil de seguridad superior",
53 => "Mayor vida media que el IGF-1 nativo\nPromueve la hipertrofia muscular\nEstimula la proliferación celular\nApoya la regeneración tisular\nMejora el metabolismo de la glucosa\nEfecto anti-apoptótico celular\nEstudiado para rendimiento deportivo",
55 => "Activa células dendríticas y linfocitos T\nPotencia la inmunidad innata y adaptativa\nAumenta la producción de citocinas Th1\nEstudiado para inmunodeficiencias\nApoya la investigación en infecciones virales\nInvestigado como adyuvante en oncología\nMejora la respuesta inmune a vacunas",
57 => "Estimulación selectiva de hormona de crecimiento\nMínimo impacto en cortisol y prolactina\nApoya la reducción de grasa corporal\nMejora la recuperación muscular\nPromueve el sueño profundo reparador\nApoya la densidad ósea y articular\nPerfil de seguridad superior entre GHRPs",
59 => "Optimiza la hidratación celular\nRegula el equilibrio electrolítico\nApoya la recuperación tisular\nMejora la resistencia y rendimiento\nModula el metabolismo celular\nEstudiado para homeostasis\nFormulación avanzada de investigación",
61 => "Actividad antimicrobiana de amplio espectro\nDesestabiliza membranas bacterianas\nModula la inmunidad innata\nPromueve la quimiotaxis de células inmunes\nEstimula la angiogénesis\nEstudiado contra biofilms resistentes\nInvestigado para curación de heridas",
63 => "Promueve la regeneración celular cutánea\nProtección contra el fotoenvejecimiento\nMejora la luminosidad y tono de la piel\nEstimula la síntesis de colágeno dérmico\nFortalece la barrera epidérmica\nActividad antioxidante\nFormulación avanzada dermatológica",
65 => "Activa la vía AMPK mitocondrial\nRegula el metabolismo de glucosa y ácidos grasos\nModula la función mitocondrial\nEstudiado para envejecimiento metabólico\nApoya el rendimiento físico\nSeñalización retrógrada mitocondria-núcleo\nInvestigado para longevidad celular",
67 => "Estabiliza la cardiolipina mitocondrial\nReduce la producción de ROS\nOptimiza la producción de ATP\nEstudiado para disfunción mitocondrial\nProtección cardíaca investigada\nApoya la investigación en sarcopenia\nInvestigado para lesión por isquemia-reperfusión",
69 => "Aumenta los niveles de energía celular (ATP)\nActiva las sirtuinas asociadas a longevidad\nApoya la reparación del ADN genómico\nCofactor en reacciones redox mitocondriales\nMejora la función cognitiva\nEstudiado para envejecimiento celular\nModula la autofagia celular",
70 => "Aumenta la expresión de BDNF cerebral\nModula sistemas dopaminérgicos y serotoninérgicos\nReduce el estrés oxidativo cerebral\nEstudiado para neuroprotección\nMejora la memoria y el aprendizaje\nApoya la recuperación neurovascular\nInvestigado para trastornos de ansiedad",
72 => "Activa receptores EPO/CD131 citoprotectores\nNeuroprotección sin efectos eritropoyéticos\nReduce la inflamación crónica\nEstudiado para neuropatía diabética\nApoya la reparación nerviosa\nInvestigado para curación de heridas crónicas\nProtección tisular en isquemia",
74 => "Sincroniza el ritmo circadiano sueño-vigilia\nPotente antioxidante directo\nModula la función inmunológica\nEstudiado para jet lag y trastornos del sueño\nProtección mitocondrial\nNeuroprotección documentada\nRegulación neuroendocrina",
76 => "Modula las ondas lentas del sueño NREM\nRegula los niveles de cortisol y ACTH\nApoya la liberación de GH durante el sueño\nEstudiado para insomnio\nNeuroprotección documentada\nModulación neuroendocrina\nMejora la calidad del descanso profundo",
78 => "Modula la señalización GABAérgica\nReduce la actividad de la amígdala\nPromueve comportamientos de vínculo social\nEstudiado para regulación del estrés\nApoya la función reproductiva\nInvestigado para trastornos del espectro autista\nMejora la regulación emocional",
80 => "Triple agonista GIP/GLP-1/glucagón\nEfecto sinérgico superior a agonistas duales\nEstimula la saciedad y secreción de insulina\nPromueve el gasto energético y lipólisis\nEstudiado para control de peso avanzado\nReducción de grasa visceral documentada\nMejora el control glucémico",
82 => "Modula el sistema GABAérgico\nAumenta la expresión de BDNF\nRegula monoaminas (serotonina, dopamina)\nEstudiado para ansiedad sin sedación\nPotencia la actividad inmunológica\nApoya la función cognitiva y memoria\nMejora la regulación del estado de ánimo",
84 => "Potente agonista del receptor GLP-1\nEstimula la secreción de insulina dependiente de glucosa\nSuprime el glucagón postprandial\nRalentiza el vaciamiento gástrico\nReduce el apetito a nivel central\nEstudiado para control de peso\nProtección cardiovascular investigada",
86 => "Activa la vía JAK2/STAT5\nEstimula la producción hepática de IGF-1\nMejora la composición corporal\nPromueve la lipólisis y reducción de grasa\nApoya la regeneración tisular\nMejora la densidad ósea\nEstudiado para deficiencia de GH",
88 => "Estimula la secreción pulsátil de GH endógena\nMayor estabilidad que la GHRH nativa\nReduce la grasa visceral abdominal\nEstudiado para lipodistrofia\nApoya la función cognitiva\nMejora la composición corporal\nInvestigado para esteatosis hepática",
90 => "Estimula la diferenciación de linfocitos T\nModula el balance Th1/Th2\nPromueve citocinas inmunorreguladoras\nApoya la regeneración del timo\nEstudiado para inmunosenescencia\nMejora la maduración de células T\nInvestigado para deficiencias inmunológicas",
92 => "Doble agonista GIP/GLP-1\nEfectos sinérgicos en pérdida de peso\nEstimula la saciedad y secreción de insulina\nMejora la sensibilidad a la insulina\nEstudiado para diabetes tipo 2\nReducción significativa de peso documentada\nProtección cardiovascular investigada",
94 => "Activa receptores VPAC1 y VPAC2\nModula la respuesta inflamatoria\nPromueve la neuroprotección\nRegula la vasodilatación\nEstudiado para enfermedades neurodegenerativas\nApoya la función gastrointestinal\nInvestigado para CIRS y biotoxinas",
];

$updated = 0;
foreach ($all_benefits as $id => $benefits) {
    update_post_meta($id, 'sp_benefits', $benefits);
    $updated++;
    echo "OK: ID $id\n";
}
echo "\nTotal: $updated benefits updated to Spanish\n";
