<?php
define('ABSPATH', dirname(__FILE__) . '/../../../');
require_once ABSPATH . 'wp-load.php';
header('Content-Type: text/plain; charset=utf-8');

$translations = [
19 => [
'short' => 'AICAR (ribonucleótido de 5-aminoimidazol-4-carboxamida) es un compuesto metabólico de investigación reconocido por su capacidad para activar la proteína quinasa activada por AMP (AMPK), un sensor energético celular clave involucrado en el metabolismo de la glucosa y los lípidos.',
'desc' => '<h3>Descripción General</h3><p>AICAR (ribonucleótido de 5-aminoimidazol-4-carboxamida) es un compuesto metabólico de investigación reconocido por su capacidad para activar la proteína quinasa activada por AMP (AMPK), un sensor energético celular clave. AMPK regula procesos fundamentales como el metabolismo de glucosa, la oxidación de ácidos grasos y la biogénesis mitocondrial.</p><h3>Mecanismo de Acción</h3><p>AicaBurn™ activa directamente la AMPK en las células, imitando los efectos del ejercicio físico a nivel molecular. Este mecanismo promueve la captación de glucosa, la oxidación de ácidos grasos y la biogénesis mitocondrial.</p><h3>Áreas de Investigación</h3><ul><li>Metabolismo de la glucosa y sensibilidad a la insulina</li><li>Oxidación de ácidos grasos y pérdida de grasa</li><li>Rendimiento en ejercicio y resistencia muscular</li><li>Biogénesis mitocondrial y producción de energía</li><li>Enfermedades metabólicas y síndrome metabólico</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
21 => [
'short' => 'AOD-9604 es un fragmento modificado de la hormona de crecimiento humano (hGH), específicamente el fragmento C-terminal (Tyr-hGH177-191). Se investiga por sus propiedades lipolíticas (quema de grasa) sin afectar los niveles de glucosa en sangre ni la proliferación celular.',
'desc' => '<h3>Descripción General</h3><p>AOD-9604 es un fragmento modificado de la hormona de crecimiento humano (hGH), específicamente el fragmento C-terminal (Tyr-hGH177-191). Es investigado por sus propiedades lipolíticas (quema de grasa) sin afectar los niveles de glucosa en sangre ni la proliferación celular.</p><h3>Mecanismo de Acción</h3><p>AOD-9604 estimula la lipólisis (descomposición de grasas) e inhibe la lipogénesis (formación de grasas) sin los efectos adversos de la hGH completa sobre el metabolismo de la glucosa.</p><h3>Áreas de Investigación</h3><ul><li>Reducción de grasa corporal y lipólisis</li><li>Regulación del metabolismo lipídico</li><li>Reparación y regeneración del cartílago</li><li>Salud ósea y articular</li><li>Terapias antiobesidad</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
23 => [
'short' => 'Cagrilintida es un análogo de acción prolongada de la amilina, una hormona peptídica cosecretada con la insulina por las células beta pancreáticas. Se estudia activamente por su papel en la regulación del control del apetito y el metabolismo gastrointestinal.',
'desc' => '<h3>Descripción General</h3><p>Appetitex™ (Cagrilintida) es un análogo de acción prolongada de la amilina, una hormona peptídica cosecretada con la insulina. Se investiga por su papel en la regulación del apetito, la saciedad y el metabolismo gastrointestinal.</p><h3>Mecanismo de Acción</h3><p>Actúa como agonista del receptor de amilina, promoviendo la saciedad a nivel central, ralentizando el vaciamiento gástrico y modulando la secreción de glucagón postprandial.</p><h3>Áreas de Investigación</h3><ul><li>Control del apetito y la saciedad</li><li>Manejo del peso corporal</li><li>Regulación de la glucosa postprandial</li><li>Terapias combinadas antiobesidad</li><li>Metabolismo gastrointestinal</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
25 => [
'short' => 'El Agua Bacteriostática es una preparación estéril y no pirogénica de agua para inyección que contiene 0.9% (9 mg/mL) de alcohol bencílico como conservante bacteriostático. Se utiliza como diluyente para la reconstitución de péptidos liofilizados.',
'desc' => '<h3>Descripción General</h3><p>El Agua Bacteriostática es una preparación estéril y no pirogénica de agua para inyección que contiene 0.9% (9 mg/mL) de alcohol bencílico añadido como conservante bacteriostático. Es el diluyente estándar para la reconstitución de péptidos liofilizados.</p><h3>Características</h3><ul><li>Estéril y no pirogénica</li><li>Conservante bacteriostático (alcohol bencílico 0.9%)</li><li>Compatible con la mayoría de péptidos de investigación</li><li>Permite múltiples extracciones del mismo vial</li><li>pH neutro y osmolaridad controlada</li></ul><h3>Uso Recomendado</h3><p>Utilizar para reconstituir péptidos liofilizados. Inyectar lentamente por la pared del vial para evitar dañar la estructura del péptido. Almacenar entre 2-8°C después de abrir.</p><h3>Especificaciones</h3><p>Volumen: 30mL por vial. Grado farmacéutico. Solo para uso en investigación.</p>'
],
27 => [
'short' => 'SNAP-8, también conocido como Acetil Octapéptido-3, es un péptido sintético derivado de la secuencia proteica SNAP-25, que desempeña un papel en la liberación de neurotransmisores en la unión neuromuscular. Se investiga por su potencial antienvejecimiento.',
'desc' => '<h3>Descripción General</h3><p>Botulift™ (SNAP-8 / Acetil Octapéptido-3) es un péptido sintético derivado de la secuencia proteica SNAP-25. Se investiga ampliamente por su potencial para modular la contracción muscular facial y reducir la formación de líneas de expresión.</p><h3>Mecanismo de Acción</h3><p>SNAP-8 actúa inhibiendo la formación del complejo SNARE, reduciendo la liberación de neurotransmisores en la unión neuromuscular y modulando la contracción muscular facial.</p><h3>Áreas de Investigación</h3><ul><li>Reducción de líneas de expresión y arrugas</li><li>Modulación neuromuscular facial</li><li>Alternativas no invasivas a las neurotoxinas</li><li>Formulaciones cosméticas avanzadas</li><li>Envejecimiento cutáneo y dermatología</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
29 => [
'short' => 'Este vial contiene una combinación sinérgica de dos péptidos de investigación: BPC-157 y TB-500, suministrados como polvo liofilizado. BPC-157 se estudia por sus propiedades regenerativas y TB-500 por su papel en la reparación tisular.',
'desc' => '<h3>Descripción General</h3><p>BPC-157 + TB-500 es una combinación sinérgica de dos péptidos de investigación suministrados como polvo liofilizado. BPC-157 se estudia por sus propiedades regenerativas y protectoras, mientras que TB-500 (Timosina Beta-4) es investigado por su papel en la reparación y regeneración tisular.</p><h3>Mecanismo de Acción</h3><p>BPC-157 modula las vías de señalización del óxido nítrico y los factores de crecimiento, mientras que TB-500 promueve la migración celular, la diferenciación y la formación de nuevos vasos sanguíneos.</p><h3>Áreas de Investigación</h3><ul><li>Reparación y regeneración de tejidos</li><li>Curación de tendones, ligamentos y músculos</li><li>Protección gastrointestinal</li><li>Reducción de inflamación sistémica</li><li>Recuperación de lesiones deportivas</li></ul><h3>Especificaciones</h3><p>Péptidos liofilizados combinados de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
31 => [
'short' => 'BPC-157 (Compuesto de Protección Corporal-157) es un pentadecapéptido sintético derivado de una proteína protectora que se encuentra naturalmente en el jugo gástrico. Se investiga ampliamente por su papel en la reparación tisular y la protección gastrointestinal.',
'desc' => '<h3>Descripción General</h3><p>BPC-Healix™ (BPC-157) es un pentadecapéptido sintético derivado de una proteína protectora encontrada naturalmente en el jugo gástrico humano. Es ampliamente investigado por sus propiedades regenerativas y citoprotectoras en múltiples sistemas del organismo.</p><h3>Mecanismo de Acción</h3><p>BPC-157 modula las vías del óxido nítrico (NO), promueve la angiogénesis y activa los factores de crecimiento implicados en la reparación tisular y la curación de heridas.</p><h3>Áreas de Investigación</h3><ul><li>Reparación de tendones, músculos y ligamentos</li><li>Protección y curación gastrointestinal</li><li>Reducción de la inflamación</li><li>Neuroprotección y regeneración nerviosa</li><li>Curación de heridas cutáneas</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
33 => [
'short' => 'Melanotan II es un análogo sintético de la hormona peptídica de melanocortina α-MSH (hormona estimulante de melanocitos alfa). Se investiga activamente por su papel en la estimulación de la melanogénesis, el proceso natural de producción de pigmento en la piel.',
'desc' => '<h3>Descripción General</h3><p>BronzeX™ (Melanotan II) es un análogo sintético de la hormona α-MSH (hormona estimulante de melanocitos alfa). Se investiga por su papel en la estimulación de la melanogénesis, el proceso natural de producción de melanina en la piel.</p><h3>Mecanismo de Acción</h3><p>Actúa como agonista no selectivo de los receptores de melanocortina (MC1R-MC5R), estimulando la producción de eumelanina en los melanocitos y activando vías de señalización relacionadas con la pigmentación cutánea.</p><h3>Áreas de Investigación</h3><ul><li>Melanogénesis y pigmentación cutánea</li><li>Fotoprotección contra radiación UV</li><li>Condiciones dermatológicas de hipopigmentación</li><li>Modulación del apetito</li><li>Función sexual y libido</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
35 => [
'short' => 'GHK-Cu (Tripéptido de Cobre-1) es un péptido de unión al cobre de origen natural compuesto por tres aminoácidos (glicina, histidina y lisina). Se investiga extensamente por su papel en la reparación tisular y la regeneración cutánea.',
'desc' => '<h3>Descripción General</h3><p>DermaCooper™ (GHK-Cu / Tripéptido de Cobre-1) es un péptido de unión al cobre de origen natural. Se investiga extensamente por su papel en la reparación tisular, la remodelación de la piel y la regeneración celular.</p><h3>Mecanismo de Acción</h3><p>GHK-Cu forma complejos con iones de cobre que modulan la expresión génica relacionada con la síntesis de colágeno, la angiogénesis, la actividad antioxidante y la señalización de reparación tisular.</p><h3>Áreas de Investigación</h3><ul><li>Síntesis de colágeno y elastina</li><li>Regeneración y reparación cutánea</li><li>Curación de heridas acelerada</li><li>Antienvejecimiento y reducción de arrugas</li><li>Crecimiento capilar y salud del cabello</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
37 => [
'short' => 'KPV (Lisina-Prolina-Valina) es un tripéptido de origen natural derivado de la secuencia C-terminal de la α-MSH. Se investiga activamente por sus potentes propiedades antiinflamatorias e inmunomoduladoras.',
'desc' => '<h3>Descripción General</h3><p>DermaKPV™ (KPV / Lisina-Prolina-Valina) es un tripéptido de origen natural derivado de la secuencia C-terminal de la α-MSH. Es investigado por sus potentes propiedades antiinflamatorias, antimicrobianas e inmunomoduladoras.</p><h3>Mecanismo de Acción</h3><p>KPV inhibe las vías de señalización inflamatoria NF-κB, reduce la producción de citocinas proinflamatorias y modula la respuesta inmune innata a nivel celular.</p><h3>Áreas de Investigación</h3><ul><li>Inflamación gastrointestinal y colitis</li><li>Modulación inmunológica</li><li>Condiciones inflamatorias de la piel</li><li>Propiedades antimicrobianas</li><li>Curación de heridas y cicatrización</li></ul><h3>Especificaciones</h3><p>Péptido liofilizado de alta pureza (≥98%). Almacenar entre 2-8°C. Solo para uso en investigación.</p>'
],
];

$updated = 0;
foreach ($translations as $id => $data) {
    $post_data = ['ID' => $id];
    if (isset($data['desc'])) $post_data['post_content'] = $data['desc'];
    if (isset($data['short'])) $post_data['post_excerpt'] = $data['short'];
    $result = wp_update_post($post_data, true);
    if (!is_wp_error($result)) {
        $updated++;
        echo "OK: ID $id updated\n";
    } else {
        echo "ERROR: ID $id - " . $result->get_error_message() . "\n";
    }
}
echo "\nTotal updated: $updated / " . count($translations) . "\n";
